### ISSUE TITLE
Does not work with Webpack v2.2.0-rc.4

### ISSUE THREAD

**Issue by nwoltman** [webpack-contrib/grunt-webpack#111]
I'm getting the following error after upgrading to Webpack v2.2.0-rc.4:

```
TypeError: arguments[i].apply is not a function
  at Compiler.apply (node_modules\tapable\lib\Tapable.js:306:16)
  at webpack (node_modules\webpack\lib\webpack.js:32:19)
  at Object.webpackDevServerTask (node_modules\grunt-webpack\tasks\webpack-dev-server.js:63:22)
```

This is happening because Webpack has changed most of their plugins to ES6 classes, which by default have non-enumerable prototype methods. `grunt-webpack` is doing some strange things with "fixing plugins" (which I'm not sure is actually necessary) and in the process is returning plugins without their `apply()` method.

### Possible Solution

Add `.getRaw` to [this line](https://github.com/webpack/grunt-webpack/blob/master/src/options/OptionHelper.js#L50).

```js
const obj = this.grunt.config.getRaw(ns) || {};
```

### Your Environment

| software         | version
| ---------------- | -------
| webpack          | >= 2.2.0-rc.4
| grunt-webpack | 2.0.0-beta.6
| grunt            | 1.0.1
| node             | 6.9.4

**Comment by danez** [comment]
I'm really tempted to remove all the custom handling of the config, which usually only done to support grunt template strings. Thanks for reporting again I'll have a look

**Comment by danez** [comment]
Which plugin die you try with? I cannot reproduce right now.

**Comment by nwoltman** [comment]
It only seems to happen with the `webpack-dev-server` task.

```js
{
  webpack: {
    // webpack config
  },

  'webpack-dev-server': {
    webpack: {
      // same config as webpack grunt task config
    },
}
```

**Comment by nwoltman** [comment]
And it's all plugins in ES6 form (https://github.com/webpack/webpack/tree/master/lib).

**Comment by unindented** [comment]
@danez Same issue with `webpack@2.2.0`. As @nwoltman says, it only happens with the `webpack-dev-server` task.

**Comment by danez** [comment]
Fixed with #117

**Comment by PatelHub** [comment]
Please, check.
i think.this issue is resolved with issue#116(https://github.com/webpack-contrib/grunt-webpack/issues/116)
If solved, please close this issue.
